version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:jessie

    working_directory: /src/bitjourney/docker-elasticsearch-ci

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Install Docker client
          environment:
            DOCKER_VERSION: "17.03.0-ce"
          command: |
            set -x
            curl -L -o /tmp/docker-$DOCKER_VERSION.tgz https://get.docker.com/builds/Linux/x86_64/docker-$DOCKER_VERSION.tgz
            tar -xz -C /tmp -f /tmp/docker-$DOCKER_VERSION.tgz
            mv /tmp/docker/* /usr/bin

      - run:
          name: Run A Container to check whether it successfully runs on CI
          environment:
            IMAGETAG: bitjourney/elasticsearch-ci:test
          command: |
            docker build -t $IMAGETAG image/
            docker run -d $IMAGETAG

      - run:
          name: Install Health Check Utility
          command: |
            apt-get update -qq
            apt-get install -y netcat

      - run:
          name: Health Check Elasticsearch from primary_container
          environment:
            HEALTH_CHECK_RETRY_LIMIT: 20
            HEALTH_CHECK_RETRY_WAIT: 3
            HEALTH_CHECK_PORT: 9200
          command: |
            for i in $(seq $HEALTH_CHECK_RETRY_LIMIT); do
              nc -vz localhost $HEALTH_CHECK_PORT || (sleep $HEALTH_CHECK_RETRY_WAIT; false) && break
            done
